name: pytest

on:
  push:
  pull_request:
    branches:
      - dev

permissions: write-all

jobs:
  setup:
    name: Run tests with pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Setup rye
        uses: eifinger/setup-rye@v1
      - name: Setup pytest
        run: |
          rye pin 3.11.5
          rye sync

      - name: Run pytest
        run: |
          set -o pipefail
          rye run pytest --junitxml=pytest.xml --cov-report=term-missing --cov=src tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
